# Data processing using Pandas...


import numpy as np
import pandas as pd


data = pd.read_csv("/report.csv", na_values = "/")                                                                          					 # Loading data from CSV file (with replacement of "/" values to NaN values)...

print(data.head(10))                                                                                                        						 # Reading first 5 rows...
print(data.tail(10))                                                                                                         						 # Reading last 10 rows...

print(data["Ispit1"])                                                                                                        						 # Reading specific column of DataFrame object
print(data["Ispit2"])

print(data.loc[data["Prisustvo"] == 0])                                                                                      					 # Reading rows with specific characteristic...

data.replace("/", np.nan, inplace = True)                                                                                    					 # Replacing values (this is only for informative purpose, these values are already replaced)...

print(data.loc[data["Ocjena"] > 7].loc[:, ["Indeks", "UKUPNO", "Ocjena"]])                                                 		      	 	 # Reading specific columns of rows with specific characteristic...
	
data.dropna(subset = ["Ocjena"], inplace = True)                                                                             					 # Deleting specific rows of DataFrame object...

temporaryStorage = data.replace(np.nan, -1)
data["Ispit1_final"] = np.maximum(temporaryStorage["Ispit1"], temporaryStorage["Ispit1_popravni"]).replace(-1, np.nan)                               # Adding new column (with specific values)...
data["Ispit2_final"] = np.maximum(temporaryStorage["Ispit2"], temporaryStorage["Ispit2_popravni"]).replace(-1, np.nan)

data.drop(columns = ["Ispit1", "Ispit2", "Ispit1_popravni", "Ispit2_popravni"], inplace = True)                              			 # Deleting specific columns of DataFrame object...

data.to_csv("report-update.csv", sep = ";")                                                                                                                                                                # Saving DataFrame object as CSV file...
data.to_pickle("report-update.p")                                                                                                                                                                               # Saving DataFrame object as Pickle file...                                                            